theme: minima
title: Mini Essays on Technology.
email: info@byothermeans.org
description: Essays and blog for Lawrence Furnival, retired associate director of information security at Teachers College, Columbia University.
twitter_username: furn
github_username: furnival
